/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/baby_groot.glb -o app/BabyGrootModel.jsx 
Author: ChrisG (https://sketchfab.com/christianguevara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baby-groot-36a1c611c5164f39a4fa7cb4faebd458
Title: Baby Groot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/baby_groot.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.0028}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Groot_LPol__0.geometry} material={materials['Scene_-_Root']} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/baby_groot.glb')
